### ISSUE TITLE
Support for other OS

### ISSUE THREAD

**Issue by Hirse** [swmitra/stackoverflow-search#1]
I just installed your extension to try it out only to realize that there is no way to use it as I am not on OSX.
Do you plan to support other OS as well?
Perhaps you could add a menu entry to the "Find"-menu, that would work everywhere.

**Comment by swmitra** [comment]
Fixed and released version 1.1.0. Thanks a lot for pointing this out. 
The new shortcut is Ctrl+Alt+W , alternatively , you can choose "Find" -> "Find in Stackoverflow.com" as menu option.
