### ISSUE TITLE
KeyBinding Error

### ISSUE THREAD

**Issue by GochoMugo** [swmitra/stackoverflow-search#2]
It seems to me that the extension is trying to bind keys\* twice (or more times).

This is the error as seen in the console (Chrome DevTools)

```
Cannot assign Ctrl-Alt-W to show.stacksearch. It is already assigned to show.stacksearch ErrorNotification.js:125
window.console.error
```

**Comment by swmitra** [comment]
Great you caught it. Fixed now. A new version 1.1.1 is available with the fix.

**Comment by GochoMugo** [comment]
**SOLVED** :+1:
